# Chapter 3: Introduction to Keras and TensorFlow

TensorFlow is more than a library, it's really a platform. \
Keras is a deep-learning API for Python, built on top of TensorFlow.\
Should run keras on GPU instead of CPU

## 3.5 First steps with TensorFlow

* Training deep learning with some concepts
    * First (In **TensorFlow**): 
        * Tensors
        * Tensor operations: like addition, relu, and matmul
        * Backpropagation: method to compute gradient.
    * Second(In **Keras**):
        * layers
        * loss functions
        * Optimizers
        * metrics to evaluate models
        * training loop
        
        

### 3.5.1 Constant tensors and Variable.

In [5]:
import numpy as np

In [3]:
# list 3.1
import tensorflow as tf
x=tf.ones(shape=(2,1))
print(x)


tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [9]:
x=tf.zeros(shape=(2,1))
print(x)
print('\n')
print(np.ones(shape=(2,1)).dtype)
#note: For tensorflow, data is usually processed as float32, but in numpy, it's as float64


tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


float64


In [10]:
#list 3.2 Random Tensors
x=tf.random.normal(shape=(3,1),mean=0., stddev=1.)
print(x)

tf.Tensor(
[[ 0.47320917]
 [ 0.17388937]
 [-1.0348241 ]], shape=(3, 1), dtype=float32)


In [11]:
x=tf.random.uniform(shape=(3,1),minval=0.,maxval=1.)
print(x)
#To form the uniform distributed data, and set minimum value=0, but maxvalue=1

tf.Tensor(
[[0.4395249 ]
 [0.57577515]
 [0.07829058]], shape=(3, 1), dtype=float32)


**Note**: TensorFlow is **not assignable**, but numpy is **assiganable**. 

In [12]:
#In numpy environment
x=np.ones(shape=(2,2))
x[0,0]=0
print(x)
#It's changed value.

[[0. 1.]
 [1. 1.]]


In [13]:
#In tensorflow environment
x=tf.one(shape=(2,2))
x[0,0]=0
print(x)
#So, the tensorflow value is not changeable, you can see the error below. 

AttributeError: module 'tensorflow' has no attribute 'one'

TensorFlow data is not changeable, but we can change it using ***tf.Variable*** where data is modified in state.

In [14]:
#list 3.5
v=tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.39716625],
       [0.35166788],
       [1.6390318 ]], dtype=float32)>


In [15]:
#list 3.6 assign a value to a variable
v.assign(tf.ones((3,1)))
#It did change!

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [16]:
#List 3.7 Assign a value to a subset of a variable
v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [17]:
# List 3.8 using assign_add
v.assign_add(tf.ones((3,1)))
#Add one to each original value

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

### 3.5.2 Tensor Operations: Doing math in TensorFlow

In [19]:
#List 3.9 A few basic math operationans
a=tf.ones((2,2))
b=tf.square(a)
c=tf.sqrt(a)
d=b+c
e=tf.matmul(a,b)# Matmul is used to multiply matrix
e *=d #Multiply two tensors (element wise)
print(c,'\n')
print(e)


tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


### 3.5.3 A second look at the GradientTape APT