# Chapter 2: The mathematical building blocks of neutral networks

In [4]:
#List 2.1 Loading the mnist datasets in keras
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()
print(train_images.shape)
print(len(train_labels))
print(test_images.shape)
print(len(test_labels))
print(train_labels)
print(test_labels)

(60000, 28, 28)
60000
(10000, 28, 28)
10000
[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [5]:
#list 2.2 The network architecture 
from tensorflow.keras  import models
from tensorflow.keras import layers
model=models.Sequential([
    layers.Dense(512,activation='relu'),
    layers.Dense(10,activation='softmax')])
#softmax layer -> the summation of 10 probability scores to 1.

**Layers** is like filtration, data in data out. layers and layers consist of deep learning

In [6]:
#List 2.3 The compilation Step
model.compile(optimizer='rmsprop',
                loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [8]:
# List 2.4Preparing the image data, aka transforming data
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255 #first to 'float32'type, then reshape the value between 0 and 1
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

Keras  use **fit** method to fit data

In [9]:
#List 2.5 'Fitting the model'
model.fit(train_images,train_labels,epochs=5,batch_size=128)
#epochs: times to fit
#Note: Very interesting thing, why does my model have less accuracy?

Epoch 1/5
469/469 [==============================] - 4s 6ms/step - loss: 1.4695 - accuracy: 0.6660
Epoch 2/5
469/469 [==============================] - 3s 6ms/step - loss: 0.5842 - accuracy: 0.8542
Epoch 3/5
469/469 [==============================] - 3s 6ms/step - loss: 0.4097 - accuracy: 0.8887
Epoch 4/5
469/469 [==============================] - 3s 7ms/step - loss: 0.3525 - accuracy: 0.9007
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.3236 - accuracy: 0.9076


In [10]:
#List 2.6 Using the model to make prediction.
test_digits=test_images[0:10]
prediction=model.predict(test_digits)
prediction[0]#predict the first image

array([2.78670559e-05, 6.27630001e-08, 1.40429365e-05, 4.98568290e-04,
       1.23577433e-06, 1.70735457e-05, 6.47814646e-09, 9.97736931e-01,
       5.41475720e-06, 1.69872167e-03], dtype=float32)

In [11]:
prediction[0].argmax() #7 has the most probability to be our target number

7

In [12]:
prediction[0][7]# the number is 7 has the probability over 99.77%

0.99773693

In [14]:
test_labels[0] #yes, it's 7! Very Accurate!

7

In [16]:
#2.7 Evaluating the model on new data
test_loss,test_acc=model.evaluate(test_images,test_labels)
print('test_acc:', test_acc)#It's okay, but still lower than the book.

313/313 [==============================] - 1s 2ms/step - loss: 0.3030 - accuracy: 0.9112
test_acc: 0.9111999869346619
